[package]
name = "reddit_pictures"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "reddit_pictures"
path = "./reddit_pictures.rs"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.23"
reqwest = "0.11.11"
scraper = "0.13.0"
tokio = { version = "1.20.1", features = ["full"] }